### ISSUE TITLE
Is there any way to use this power button script with a RASPI4 running Windows 10?

### ISSUE THREAD

**Issue by saladosia** [okunze/Argon40-ArgonOne-Script#1]

**Comment by okunze** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}I am not aware of any way to make this script run on Windows 10.

**Comment by okunze** [comment]
I am not aware of any way to make this script run on Windows 10.
